# Mặc định khi ấn nút Run trên VS Code sẽ chạy môi trường 'dev'
spring.profiles.active=dev

# (Bạn có thể để các cấu hình dùng chung cho cả 2 bên ở file này, ví dụ:)
spring.servlet.multipart.max-file-size=5MB