spring.application.name=website
# Cấu hình Database H2 chạy tạm trên RAM (Mất dữ liệu khi tắt server)
spring.datasource.url=jdbc:h2:mem:pesocdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Cho phép xem giao diện quản lý database tại trình duyệt
spring.h2.console.enabled=true
# Tự động tạo bảng từ các Class có dấu @Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true