# 1. Đường dẫn lưu file: Lưu vào thư mục 'data' ngay trong dự án
spring.datasource.url=jdbc:h2:file:./data/pesocdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 2. Quan trọng: Giữ lại dữ liệu cũ, chỉ cập nhật thêm cái mới
spring.jpa.hibernate.ddl-auto=update

# 3. Cho phép xem giao diện quản lý Database trên trình duyệt
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# 4. Hiển thị các câu lệnh SQL dưới Console để b dễ theo dõi
spring.jpa.show-sql=false
# Ép Spring chạy script SQL sau khi đã tạo bảng xong
spring.jpa.defer-datasource-initialization=false

# Ép buộc chạy script khởi tạo dữ liệu trong mọi trường hợp
spring.sql.init.mode=never

# Giới hạn dung lượng tối đa cho 1 file tải lên (Ví dụ: 2 Megabyte)
spring.servlet.multipart.max-file-size=2MB
# Giới hạn tổng dung lượng của toàn bộ request tải lên
spring.servlet.multipart.max-request-size=2MB